version: '3'

services:
  pricing:
    image: pricing_image
    container_name: pricing_dev
    ports:
      - "8888:8888"
    stdin_open: true
    tty: true
    volumes:
      - .:/home/pricing
    environment:
      PRICING_API_HOST: http://10.2.142.113:3000/
      PRICING_API_USER: pricing_api_username
      PRICING_API_PASSWORD: 7b4ps434fku4uxxehak5dr3qpe3k8472
      PYTHONPATH: /home/pricing/src
